version: '3'

services:
  reverse-proxy:
    image: traefik:latest
    command:
      # Montar o sock dentro do traefik
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"

      # Modo Swarm Ativiado
      - "--providers.docker.swarmMode=true"
      
      # Serviço não será exposto por default, deverá ser incluido alguns labels (enable)
      - "--providers.docker.exposedbydefault=false"
      
      # Incluir a rede do Docker
      - "--providers.docker.network=traefik-public"
      
      # Porta de requisições (Gateway de Entrada)
      - "--entrypoints.web.address=:80"
    ports:
     - 80:80
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          # Traefik vai executar somente em nodes manager
          - node.role == manager

networks:
  traefik-public:
