version: "3"
services:
  web:
    image: nginx
    deploy:
      placement:
        constraints:
        - node.labels.dc == SP
      replicas: 6
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
    - "8082:80"
    networks:
    - webserver

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
    - "8088:8080"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
    - webserver

networks:
  webserver:
